package mcp

import (
	"context"
	"fmt"
	"time"

	"github.com/company/smartticket/internal/ticket"
)

// ----------------------------------------------------------------------------
// Local output views
// ----------------------------------------------------------------------------
//
// messageResponse is a flat, schema-safe MCP view of a ticket message. It
// mirrors ticket.MessageResponse but lives in the MCP package so the go-sdk's
// output schema inference never traverses the GORM model graph.

// messageResponse is the cycle-safe, schema-safe MCP view of a ticket message.
type messageResponse struct {
	ID          uint      `json:"id" jsonschema:"the message's numeric ID"`
	TicketID    uint      `json:"ticket_id" jsonschema:"the ID of the ticket the message belongs to"`
	UserID      uint      `json:"user_id" jsonschema:"the ID of the user who posted the message"`
	Content     string    `json:"content" jsonschema:"the message body"`
	ContentType string    `json:"content_type" jsonschema:"the content type: text, html or markdown"`
	IsInternal  bool      `json:"is_internal" jsonschema:"whether the message is an internal note (hidden from customers)"`
	IsFromAI    bool      `json:"is_from_ai" jsonschema:"whether the message was generated by AI"`
	CreatedAt   time.Time `json:"created_at" jsonschema:"when the message was created"`
}

// messageResponseFrom converts a service-layer ticket.MessageResponse into the
// schema-safe MCP view.
func messageResponseFrom(r *ticket.MessageResponse) messageResponse {
	if r == nil {
		return messageResponse{}
	}
	return messageResponse{
		ID:          r.ID,
		TicketID:    r.TicketID,
		UserID:      r.UserID,
		Content:     r.Content,
		ContentType: r.ContentType,
		IsInternal:  r.IsInternal,
		IsFromAI:    r.IsFromAI,
		CreatedAt:   r.CreatedAt,
	}
}

// messageListOutput is the schema-safe MCP view of a ticket's messages. The Data
// slice carries omitempty so an empty list marshals to an omitted field rather
// than JSON null.
type messageListOutput struct {
	Data  []messageResponse `json:"data,omitempty" jsonschema:"the ticket's messages, oldest first"`
	Total int               `json:"total" jsonschema:"total number of messages returned"`
}

// ----------------------------------------------------------------------------
// ticket_message_create
// ----------------------------------------------------------------------------

// ticketMessageCreateInput is the MCP input schema for ticket_message_create.
type ticketMessageCreateInput struct {
	TicketID    uint   `json:"ticket_id" jsonschema:"the numeric ID of the ticket to post the reply on (required)"`
	Content     string `json:"content" jsonschema:"the message body (required)"`
	ContentType string `json:"content_type,omitempty" jsonschema:"content type: one of text, html, markdown (defaults to text)"`
	IsInternal  bool   `json:"is_internal,omitempty" jsonschema:"whether the message is an internal note (hidden from customers)"`
}

// ticketMessageCreate posts a reply on a ticket on behalf of the acting session
// user. It delegates to the ticket service, so the service-layer notification
// hook fires normally.
func ticketMessageCreate(ctx context.Context, b Backend, in ticketMessageCreateInput) (messageResponse, string, error) {
	session, ok := SessionFromContext(ctx)
	if !ok || session == nil {
		return messageResponse{}, "", ErrUnauthenticated
	}

	req := &ticket.CreateMessageRequest{
		Content:     in.Content,
		ContentType: in.ContentType,
		IsInternal:  in.IsInternal,
	}

	resp, err := b.CreateMessage(session.Actor(), in.TicketID, session.UserID, req)
	if err != nil {
		return messageResponse{}, "", err
	}
	return messageResponseFrom(resp), fmt.Sprintf("posted reply #%d on ticket #%d", resp.ID, resp.TicketID), nil
}

// ----------------------------------------------------------------------------
// ticket_message_list
// ----------------------------------------------------------------------------

// ticketMessageListInput is the MCP input schema for ticket_message_list.
type ticketMessageListInput struct {
	TicketID uint `json:"ticket_id" jsonschema:"the numeric ID of the ticket whose messages to list (required)"`
}

// ticketMessageList lists the messages on a ticket, scoped to the acting
// session's customer.
func ticketMessageList(ctx context.Context, b Backend, in ticketMessageListInput) (messageListOutput, string, error) {
	msgs, err := b.ListMessages(sessionActor(ctx), in.TicketID)
	if err != nil {
		return messageListOutput{}, "", err
	}

	out := messageListOutput{Total: len(msgs)}
	if len(msgs) > 0 {
		out.Data = make([]messageResponse, len(msgs))
		for i := range msgs {
			out.Data[i] = messageResponseFrom(&msgs[i])
		}
	}
	return out, fmt.Sprintf("listed %d message(s) on ticket #%d", len(msgs), in.TicketID), nil
}
